package foo.main

import foo.UserWithRegion
import foo.codec.{AvroDecoder, Decoder}

object AvroDecoderForUserWithRegion { // This could be generated by Macro
  implicit val decoderForUserWithRegion: Decoder[UserWithRegion] = AvroDecoder[UserWithRegion]
}
